/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * 
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user guide at https://docs.gradle.org/4.9/userguide/multi_project_builds.html
 */
rootProject.name = "mcMMO"
include("core", "bukkit", "sponge")

pluginManagement {
    repositories {
        jcenter()
        maven("https://repo.spongepowered.org/maven/")
        gradlePluginPortal()
    }
}
