name: mcMMO
main: com.gmail.nossr50.mcMMO
version: ${project.version}-b${BUILD_NUMBER}
softdepend: [Spout]
authors:
  - TheYeti
  - nossr50
  - NuclearW
  - gmcferrin
description: mcMMO takes core Minecraft game mechanics and expands them to add an extensive RPG experience, the goal of the project has always been a quality RPG experience. Everything in mcMMO is carefully thought out and is constantly improving. mcMMO adds eleven skills to train in and level in, while also offering a high level of customization for server admins. There are countless features, including custom sounds, graphical elements, and more added when running mcMMO in conjunction with Spout. I carefully read feedback and evaluate the mechanics of mcMMO in every update to provide an ever-evolving experience.
commands:
    mchud:
        description: Change your HUD
    xplock:
        description: Lock your xp bar
    xprate:
        description: Modify the xp rate or start an event
    mcc:
        description: Lists mcMMO commands
    mcmmo:
        description: Shows a brief mod description
    mctop:
        description: Shows leader boards for mcMMO
    addxp:
        description: Add XP to a user
        permission: mcmmo.tools.mmoedit
    addlevels:
        description: Add levels to a user
        permission: mcmmo.tools.mmoedit
    mcability:
        description: Toggle whether or not abilities get readied on right click
        permission: mcmmo.commands.ability
    mcrefresh:
        description: Refresh all cooldowns for mcMMO
        permission: mcmmo.tools.mcrefresh
    mcgod:
        description: Make yourself invulnerable
        permission: mcmmo.tools.mcgod        
    mcstats:
        description: Shows your mcMMO stats and xp
    mcremove:
        description: Remove a user from the database
        permission: mcmmo.tools.mcremove
    mmoedit:
        description: Edit the skill values for a user
        permission: mcmmo.tools.mmoedit
    ptp:
        description: Teleport to a party member
        permission: mcmmo.commands.ptp
    party:
        description: Create/join a party
        permission: mcmmo.commands.party
    inspect:
        description: View mcMMO stats of another player
    invite:
        description: Invite a player into your party
        permission: mcmmo.chat.partychat
    accept:
        description: Accept a party invite
        permission: mcmmo.chat.partychat
    mmoupdate:
        description: Convert from Flat File to MySQL
        permission: mcmmo.admin
    p:
        description: Toggle Party chat or send party chat messages
        permission: mcmmo.chat.partychat
    excavation:
        description: Detailed skill info
    herbalism:
        description: Detailed skill info
    mining:
        description: Detailed skill info
    woodcutting:
        description: Detailed skill info
    axes:
        description: Detailed skill info
    archery:
        description: Detailed skill info
    swords:
        description: Detailed skill info
    taming:
        description: Detailed skill info
    unarmed:
        description: Detailed skill info
    acrobatics:
        description: Detailed skill info
    repair:
        description: Detailed skill info
    fishing:
        description: Detailed skill info
    a:
        description: Toggle Admin chat or send admin chat messages
        permission: mcmmo.chat.adminchat
permissions:
    mcmmo.*:
        description: Implies all mcmmo permissions.
        children:
            mcmmo.defaults: true
            #Instead of containing mcmmo.defaultsop on its own, it should specify each of mcmmo.defaultsop
            mcmmo.admin: true
            mcmmo.tools.*: true
            mcmmo.chat.adminchat: true
    mcmmo.defaults:
        default: true
        description: mcmmo permisions that default to true
        children:
            mcmmo.ability.*: true 
            mcmmo.item.*: true   
            mcmmo.motd: true 
            mcmmo.commands.*: true 
            mcmmo.chat.partychat: true 
            mcmmo.skills.*: true
    mcmmo.defaultsop:
        default: op
        description: mcmmo permissions that default to op
        children:
            mcmmo.chat.adminchat: true
            mcmmo.admin: true
            mcmmo.tools.*: true
    mcmmo.admin:
        description: Allows access to mmoupdate and other sensitive commands        
    mcmmo.bypass.arcanebypass:
        description: Allows user to bypass Arcane Repair so he will never lose enchantments
    mcmmo.tools.*:
        description: Implies all mcmmo.tools permissions.
        children:
            mcmmo.tools.mcrefresh: true 
            mcmmo.tools.mmoedit: true 
            mcmmo.tools.mcgod: true
            mcmmo.tools.mcremove: true
    mcmmo.tools.mcrefresh:
        description: Allows access to mcrefresh command
    mcmmo.tools.mmoedit:
        description: Allows access to mmoedit command
    mcmmo.tools.mcgod:
        description: Allows access to mcgod command
    mcmmo.tools.mcremove:
        decription: Allows access to mcremove command
    mcmmo.ability.*:
        description: Implies all mcmmo.ability permissions.
        children:
            mcmmo.ability.taming.*: true
            mcmmo.ability.fishing.*: true
            mcmmo.ability.mining.*: true
            mcmmo.ability.woodcutting.*: true
            mcmmo.ability.repair.*: true
            mcmmo.ability.unarmed.*: true
            mcmmo.ability.archery.*: true
            mcmmo.ability.herbalism.*: true
            mcmmo.ability.excavation.*: true
            mcmmo.ability.swords.*: true
            mcmmo.ability.axes.*: true
            mcmmo.ability.acrobatics.*: true
            mcmmo.ability.blastmining.*: true
    mcmmo.ability.taming.*:
        description: Allows access to all Taming abilities
        children:
            mcmmo.ability.taming.fastfoodservice: true
            mcmmo.ability.taming.sharpenedclaws: true
            mcmmo.ability.taming.gore: true
            mcmmo.ability.taming.callofthewild: true
            mcmmo.ability.taming.environmentallyaware: true
            mcmmo.ability.taming.thickfur: true
            mcmmo.ability.taming.shockproof: true
            mcmmo.ability.taming.beastlore: true
    mcmmo.ability.taming.fastfoodservice:
        description: Allows access to the Fast Food Service ability
    mcmmo.ability.taming.sharpenedclaws:
        description: Allows access to the Sharpened Claws ability
    mcmmo.ability.taming.gore:
        description: Allows access to the Gore ability
    mcmmo.ability.taming.callofthewild:
        description: Allows access to the Call of the Wild ability
    mcmmo.ability.taming.environmentallyaware:
        description: Allows access to the Environmentally Aware ability
    mcmmo.ability.taming.thickfur:
        description: Allows access to the Thick Fur ability
    mcmmo.ability.taming.shockproof:
        description: Allows access to the Shock Proof ability
    mcmmo.ability.taming.beastlore:
        description: Allows access to the Beast Lore ability
    mcmmo.ability.fishing.*:
        description: Allows access to all Fishing abilities
        children:
            mcmmo.ability.fishing.shakemob: true
    mcmmo.ability.fishing.shakemob:
        description: Allows access to the Shake Mob ability
    mcmmo.ability.mining.*:
        description: Allows access to all Mining abilities
        children:
            mcmmo.ability.mining.superbreaker: true
            mcmmo.ability.mining.doubledrops: true
    mcmmo.ability.mining.superbreaker:
        description: Allows access to the Super Breaker ability
    mcmmo.ability.mining.doubledrops:
        description: Allows double drop chance when mining
    mcmmo.ability.woodcutting.*:
        description: Allows access to all Woodcutting abilities
        children:
            mcmmo.ability.woodcutting.treefeller: true
            mcmmo.ability.woodcutting.leafblower: true
            mcmmo.ability.woodcutting.doubledrops: true
    mcmmo.ability.woodcutting.treefeller:
        description: Allows access to Tree Feller ability
    mcmmo.ability.woodcutting.leafblower:
        description: Allows access to Leaf Blower ability
    mcmmo.ability.woodcutting.doubledrops:
        description: Allows double drop chance when woodcutting
    mcmmo.ability.repair.*:
        description: Allows access to all Repair abilities
        children:
            mcmmo.ability.repair.repairbonus: true
            mcmmo.ability.repair.arcaneforging: true
            mcmmo.ability.repair.stonerepair: true
            mcmmo.ability.repair.ironrepair: true
            mcmmo.ability.repair.goldrepair: true
            mcmmo.ability.repair.diamondrepair: true
            mcmmo.ability.repair.armorrepair: true
            mcmmo.ability.repair.toolrepair: true
    mcmmo.ability.repair.repairbonus:
        description: Allows access to Super Repair bonus
    mcmmo.ability.repair.arcaneforging:
        description: Allows access to the Arcane Forging ability
    mcmmo.ability.repair.stonerepair:
        description: Allows ability to repair Stone tools
    mcmmo.ability.repair.ironrepair:
        description: Allows ability to repair Iron tools & armor
    mcmmo.ability.repair.goldrepair:
        description: Allows ability to repair Gold tools & armor
    mcmmo.ability.repair.diamondrepair:
        description: Allows ability to repair Diamond tools & armor
    mcmmo.ability.repair.armorrepair:
        description: Allows ability to repair armor
    mcmmo.ability.repair.toolrepair:
        description: Allows ability to repair tools
    mcmmo.ability.unarmed.*:
        description: Allows access to all Unarmed abilities
        children:
            mcmmo.ability.unarmed.bonusdamage: true
            mcmmo.ability.unarmed.disarm: true
            mcmmo.ability.unarmed.berserk: true
            mcmmo.ability.unarmed.deflect: true
    mcmmo.ability.unarmed.bonusdamage:
        description: Allows bonus damage from Unarmed
    mcmmo.ability.unarmed.disarm:
        description: Allows access to the Disarm ability
    mcmmo.ability.unarmed.berserk:
        description: Allows access to the Berserker ability
    mcmmo.ability.unarmed.deflect:
        description: Allows access to the Deflect ability
    mcmmo.ability.archery.*:
        description: Allows access to all Archery abilities
        children:
            mcmmo.ability.archery.trackarrows: true
            mcmmo.ability.archery.ignition: true
            mcmmo.ability.archery.daze: true
    mcmmo.ability.archery.trackarrows:
        description: Allows tracking & retrieval of arrows
    mcmmo.ability.archery.ignition:
        description: Allows access to the Ignition ability
    mcmmo.ability.archery.daze:
        description: Allows access to the Daze ability
    mcmmo.ability.herbalism.*:
        description: Allows access to all Herbalism abilities
        children:
            mcmmo.ability.herbalism.doubledrops: true
            mcmmo.ability.herbalism.greenterra: true
            mcmmo.ability.herbalism.greenthumbblocks: true
            mcmmo.ability.herbalism.greenthumbwheat: true
    mcmmo.ability.herbalism.doubledrops:
        description: Allows double drop chance from Herbalism
    mcmmo.ability.herbalism.greenterra:
        description: Allows access to the Green Terra ability
    mcmmo.ability.herbalism.greenthumbblocks:
        description: Allows access to the Green Thumb ability for blocks
    mcmmo.ability.herbalism.greenthumbwheat:
        description: Allows access to the Green Thumb ability for wheat
    mcmmo.ability.excavation.*:
        description: Allows access to all Excavation abilities
        children:
            mcmmo.ability.excavation.gigadrillbreaker: true
            mcmmo.ability.excavation.treasures: true
    mcmmo.ability.excavation.gigadrillbreaker:
        description: Allows access to the Giga Drill Breaker ability
    mcmmo.ability.excavation.treasures:
        description: Allows treasure drops from Excavation
    mcmmo.ability.swords.*:
        description: Allows access to all Swords abilities
        children:
            mcmmo.ability.swords.bleed: true
            mcmmo.ability.swords.serratedstrikes: true
            mcmmo.ability.swords.counterattack: true
    mcmmo.ability.swords.bleed:
        description: Allows access to the Bleed ability
    mcmmo.ability.swords.serratedstrikes:
        description: Allows access to the Serrated Strikes ability
    mcmmo.ability.swords.counterattack:
        description: Allows access to the Counter Attack ability
    mcmmo.ability.axes.*:
        description: Allows access to all Axes abilities
        children:
            mcmmo.ability.axes.skullsplitter: true
            mcmmo.ability.axes.bonusdamage: true
            mcmmo.ability.axes.criticalhit: true
            mcmmo.ability.axes.impact: true
    mcmmo.ability.axes.skullsplitter:
        description: Allows access to the Skull Splitter ability
    mcmmo.ability.axes.bonusdamage:
        description: Allows bonus damage from Axes
    mcmmo.ability.axes.criticalhit:
        description: Allows access to the Critical Hit ability
    mcmmo.ability.axes.skullsplitter:
        description: Allows access to the Impact ability
    mcmmo.ability.acrobatics.*:
        description: Allows access to all Acrobatics abilities
        children:
            mcmmo.ability.acrobatics.roll: true
            mcmmo.ability.acrobatics.gracefulroll: true
            mcmmo.ability.acrobatics.dodge: true
    mcmmo.ability.acrobatics.roll:
        description: Allows access to the Roll ability
    mcmmo.ability.acrobatics.gracefulroll:
        description: Allows access to the Graceful Roll ability
    mcmmo.ability.acrobatics.dodge:
        description: Allows access to the Dodge ability
    mcmmo.ability.blastmining.*:
        description: Allows access to all Blast Mining abilities
        children:
            mcmmo.ability.blastmining.biggerbombs: true
            mcmmo.ability.blastmining.demolitionsexpertise: true
    mcmmo.ability.blastmining.biggerbombs:
        description: Allows access to the Bigger Bombs ability
    mcmmo.ability.blastmining.demolitionsexpertise:
        description: Allows access to the Demolitions Expertise ability
    mcmmo.item.*:
        description: Implies all mcmmo.item permissions.
        children:
            mcmmo.item.chimaerawing: true 
    mcmmo.item.chimaerawing:
        description: Allows use of Chimaera Wing item
    mcmmo.motd:
        description: Allows access to the motd        
    mcmmo.commands.*:
        description: Implies all mcmmo.commands permissions.
        children:
            mcmmo.commands.ability: true  
            mcmmo.commands.ptp: true 
            mcmmo.commands.inspect: true 
            mcmmo.commands.party: true 
    mcmmo.commands.ability:
        description: Allows access to the mcability command
    mcmmo.commands.ptp:
        description: Allows access to the ptp command
    mcmmo.commands.inspect:
        description: Allows access to the inspect command
    mcmmo.commands.party:
        description: Allows acces to the party command        
    mcmmo.chat.*:
        description: Implies all mcmmo.chat permissions. (Warning, contains adminchat)
        children:
            mcmmo.chat.adminchat: true 
            mcmmo.chat.partychat: true 
    mcmmo.chat.adminchat:
        description: Allows participation in admin chat
    mcmmo.chat.partychat:
        description: Allows participation in party chat
    mcmmo.skills.*:
        description: Implies all mcmmo.skills permissions.
        children:
            mcmmo.skills.fishing: true
            mcmmo.skills.taming: true 
            mcmmo.skills.mining: true 
            mcmmo.skills.woodcutting: true 
            mcmmo.skills.repair: true 
            mcmmo.skills.unarmed: true 
            mcmmo.skills.archery: true 
            mcmmo.skills.herbalism: true 
            mcmmo.skills.excavation: true 
            mcmmo.skills.swords: true 
            mcmmo.skills.axes: true 
            mcmmo.skills.acrobatics: true
            mcmmo.skills.blastmining: true
    mcmmo.skills.fishing:
        description: Allows access to the Fishing skill
    mcmmo.skills.taming:
        description: Allows access to the Taming skill
    mcmmo.skills.mining:
        description: Allows access to the Mining skill
    mcmmo.skills.woodcutting:
        description: Allows access to the Woodcutting skill
    mcmmo.skills.repair:
        description: Allows access to the Repair skill
    mcmmo.skills.unarmed:
        description: Allows access to the Unarmed skill
    mcmmo.skills.archery:
        description: Allows access to the Archery skill
    mcmmo.skills.herbalism:
        description: Allows access to the Herbalism skill
    mcmmo.skills.excavation:
        description: Allows access to the Excavation skill
    mcmmo.skills.swords:
        description: Allows access to the Swords skill
    mcmmo.skills.axes:
        description: Allows access to the Axes skill
    mcmmo.skills.acrobatics:
        description: Allows access to the Acrobatics skill
    mcmmo.skills.blastmining:
        description: Allows access to the Blast Mining subskill for Mining